# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  publish-testpypi:
    if: github.event.release.prerelease
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://pypi.org/p/pynntp
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - run: pipx install poetry
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Bump version
        run: |
          poetry version ${{ github.event.release.tag_name }}

      - name: Build package
        run: poetry build

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/

  publish-pypi:
    if: "!github.event.release.prerelease"
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/pynntp
    permissions:
      id-token: write
      contents: write

    steps:
      - uses: actions/checkout@v4
      - run: pipx install poetry
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Bump version
        run: |
          poetry version ${{ github.event.release.tag_name }}

      - name: Build package
        run: poetry build

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1

      - name: Commit version change
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
          git commit -am "Bump version to ${{ github.event.release.ref_name }}"
          git push
